FROM almalinux:9

RUN mkdir -p /code && \
    dnf update -y && \
    dnf clean all
RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o wait_for_it.sh && chmod +x wait_for_it.sh
COPY ./alws/scripts/tests_cacher/requirements.txt /code/requirements.txt
RUN cd /code && python3 -m venv env && source env/bin/activate && \
    pip3 install --upgrade pip && pip3 install -r /code/requirements.txt --no-cache-dir
WORKDIR /code
CMD ["/bin/bash", "-c", "source env/bin/activate && pip3 install --upgrade pip && pip3 install -r requirements.txt --no-cache-dir && python tests_cacher.py"]

