---
mqtt_queue_host: 127.0.0.1
mqtt_queue_port: 1883
mqtt_queue_topic_unmodified: gitea-webhooks-unmodified
mqtt_queue_topic_modified: gitea-webhooks-modified
mqtt_queue_qos: 2
mqtt_client_id: albs_gitea_listener
mqtt_queue_username: gitealistener
mqtt_queue_password: somewerystr0ngpa$$wd
mqtt_queue_clean_session: False
albs_jwt_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmVzIjoxMDE2Mjc5ODUyNzkuNDg2NjUsImlkZW50aXR5Ijp7InVzZXJfaWQiOjF9fQ.PAKgKQhzcmPKbAcj2yvE5LX822oYxZL_I_73YMy8LuA
albs_address: http://127.0.0.1:8080
