"""Added priority arches to copy in release

Revision ID: 077264687344
Revises: 970f3174985b
Create Date: 2022-03-29 10:01:32.470281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '077264687344'
down_revision = '970f3174985b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('copy_priority_arches', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'copy_priority_arches')
    # ### end Alembic commands ###
