"""Create 'Distribution instance'

Revision ID: 09647b29300e
Revises: d5fe69a50d11
Create Date: 2021-09-29 16:47:21.152274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09647b29300e"
down_revision = "d5fe69a50d11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_distributions_name"), "distributions", ["name"], unique=True
    )
    op.create_table(
        "distribution_repositories",
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["distribution_id"], ["distributions.id"],),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"],),
        sa.PrimaryKeyConstraint("distribution_id", "repository_id"),
    )
    op.create_table(
        "platform_dependency",
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["distribution_id"], ["distributions.id"],),
        sa.ForeignKeyConstraint(["platform_id"], ["platforms.id"],),
        sa.PrimaryKeyConstraint("distribution_id", "platform_id"),
    )
    op.create_table(
        "distribution_packages",
        sa.Column("distribution_id", sa.Integer(), nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["builds.id"],),
        sa.ForeignKeyConstraint(["distribution_id"], ["distributions.id"],),
        sa.PrimaryKeyConstraint("distribution_id", "build_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("distribution_packages")
    op.drop_table("platform_dependency")
    op.drop_table("distribution_repositories")
    op.drop_index(op.f("ix_distributions_name"), table_name="distributions")
    op.drop_table("distributions")
    # ### end Alembic commands ###
