"""Add ts field to SignTask

Revision ID: 1d899c52d522
Revises: add07ec9f86d
Create Date: 2022-04-05 20:54:48.089898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d899c52d522"
down_revision = "add07ec9f86d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sign_tasks", sa.Column("ts", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sign_tasks", "ts")
    # ### end Alembic commands ###
