"""Added builds and repos for Product

Revision ID: 1f68a6981a68
Revises: 761f4aae2712
Create Date: 2022-07-19 15:12:56.315536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f68a6981a68'
down_revision = '761f4aae2712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_repositories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_repositories_products_id'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name='fk_product_repositories_repositories_id'),
    sa.PrimaryKeyConstraint('product_id', 'repository_id')
    )
    op.create_table('product_packages',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name='fk_product_packages_builds_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_packages_products_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'build_id')
    )
    op.create_table('product_platforms',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name='fk_product_platforms_platforms_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_platforms_products_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'platform_id')
    )
    op.alter_column('build_releases', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('builds', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # FIXME: Change nullable to False after Product population
    op.add_column('products', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('builds', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('build_releases', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('product_packages')
    op.drop_table('product_repositories')
    op.drop_table('product_platforms')
    op.drop_column('products', 'description')
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
