"""

Revision ID: 20c61e4269ef
Revises: fad009ddf89a
Create Date: 2022-07-18 16:19:54.227739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c61e4269ef'
down_revision = 'fad009ddf89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_repositories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'repository_id')
    )
    op.create_table('product_packages',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'build_id')
    )
    op.alter_column('build_releases', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('builds', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('builds', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('build_releases', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('product_packages')
    op.drop_table('product_repositories')
    # ### end Alembic commands ###
