"""Added module column to ErrataRecord

Revision ID: 237d7e07633e
Revises: 8548c94241d9
Create Date: 2023-02-22 09:16:28.249922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237d7e07633e'
down_revision = '8548c94241d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errata_records', sa.Column('module', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('errata_records', 'module')
    # ### end Alembic commands ###
