"""Adding fkeys for sign PGP keys for RPM.packages


Revision ID: 284da0d3ed87
Revises: aa0a3bdf68d4
Create Date: 2022-01-21 12:29:25.353118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284da0d3ed87'
down_revision = 'aa0a3bdf68d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binary_rpms', sa.Column('signed_by_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key('binary_rpms_signed_by_key_id_fkey', 'binary_rpms', 'sign_keys', ['signed_by_key_id'], ['id'])
    op.add_column('source_rpms', sa.Column('signed_by_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key('source_rpms_signed_by_key_id_fkey', 'source_rpms', 'sign_keys', ['signed_by_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_rpms_signed_by_key_id_fkey', 'source_rpms', type_='foreignkey')
    op.drop_column('source_rpms', 'signed_by_key_id')
    op.drop_constraint('binary_rpms_signed_by_key_id_fkey', 'binary_rpms', type_='foreignkey')
    op.drop_column('binary_rpms', 'signed_by_key_id')
    # ### end Alembic commands ###
