"""Add build tasks filtering in release plan gathering

Revision ID: 2e1d89155486
Revises: e88b665182b9
Create Date: 2021-12-23 09:34:19.562458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1d89155486'
down_revision = 'e88b665182b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_releases', sa.Column('build_task_ids', sa.ARRAY(sa.Integer(), dimensions=1), nullable=True))
    op.add_column('build_releases', sa.Column('reference_platform_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_releases', 'reference_platform_id')
    op.drop_column('build_releases', 'build_task_ids')
    # ### end Alembic commands ###
