"""Add stats for test tasks

Revision ID: 2f2ff62c7d91
Revises: e2a858195e3a
Create Date: 2023-02-23 13:43:22.378415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f2ff62c7d91'
down_revision = 'e2a858195e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_tasks', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('test_tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('test_tasks', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('test_tasks', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_tasks', 'stats')
    op.drop_column('test_tasks', 'finished_at')
    op.drop_column('test_tasks', 'started_at')
    op.drop_column('test_tasks', 'scheduled_at')
    # ### end Alembic commands ###
