"""Added reference platforms

Revision ID: 314527b431de
Revises: 6f8e782397d2
Create Date: 2022-02-10 20:26:50.311033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '314527b431de'
down_revision = '6f8e782397d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('distr_type', sa.Text(), nullable=False),
    sa.Column('distr_version', sa.Text(), nullable=False),
    sa.Column('arch_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_platforms_name'), 'reference_platforms', ['name'], unique=True)
    op.add_column('platforms', sa.Column('reference_platform', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'reference_platform')
    op.drop_index(op.f('ix_reference_platforms_name'), table_name='reference_platforms')
    op.drop_table('reference_platforms')
    # ### end Alembic commands ###
