"""Added stats for releases

Revision ID: 3770d10ce787
Revises: 237d7e07633e
Create Date: 2023-03-09 11:24:04.920417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3770d10ce787'
down_revision = '237d7e07633e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_releases', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('build_releases', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('performance_stats', sa.Column('release_id', sa.Integer(), nullable=True))
    op.create_foreign_key('perf_stats_build_release_id', 'performance_stats', 'build_releases', ['release_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('perf_stats_build_release_id', 'performance_stats', type_='foreignkey')
    op.drop_column('performance_stats', 'release_id')
    op.drop_column('build_releases', 'finished_at')
    op.drop_column('build_releases', 'started_at')
    # ### end Alembic commands ###
