"""Add test tasks artifacts table

Revision ID: 38cb9a229d07
Revises: c221ef0efa07
Create Date: 2021-10-06 12:30:11.597243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cb9a229d07'
down_revision = 'c221ef0efa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_task_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_task_id'], ['test_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test_tasks', sa.Column('repository_id', sa.Integer(), nullable=True))
    op.create_foreign_key('test_task_repo_fk', 'test_tasks', 'repositories', ['repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_task_repo_fk', 'test_tasks', type_='foreignkey')
    op.drop_column('test_tasks', 'repository_id')
    op.drop_table('test_task_artifacts')
    # ### end Alembic commands ###
