"""Add error message to task

Revision ID: 433fd427f579
Revises: 1d899c52d522
Create Date: 2022-04-21 12:47:58.790011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "433fd427f579"
down_revision = "1d899c52d522"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("build_tasks", sa.Column("error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("build_tasks", "error")
    # ### end Alembic commands ###
