"""RBAC for signing and releasing

Revision ID: 46393610f521
Revises: 761f4aae2712
Create Date: 2022-07-25 12:07:27.479853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46393610f521'
down_revision = '63a8cf1a53ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'platform_role_mapping',
        sa.Column('platform_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['platform_id'], ['platforms.id'],
            name='platform_role_mapping_platform_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['role_id'], ['user_roles.id'],
            name='platform_role_mapping_user_id_fkey'
        ),
        sa.PrimaryKeyConstraint('platform_id', 'role_id')
    )
    op.add_column('build_releases', sa.Column('team_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_releases', 'team_id')
    op.drop_table('platform_role_mapping')
    # ### end Alembic commands ###
