"""codenotary integration

Revision ID: 469f4e07ae80
Revises: cb0a65b84b4c
Create Date: 2022-06-24 14:33:53.654230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469f4e07ae80'
down_revision = 'cb0a65b84b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_artifacts', sa.Column('cas_hash', sa.Text(), nullable=True))
    op.add_column('build_tasks', sa.Column('alma_commit_cas_hash', sa.Text(), nullable=True))
    op.add_column('build_tasks', sa.Column('is_cas_authenticated', sa.Boolean(), nullable=True))
    op.add_column('build_task_refs', sa.Column('git_commit_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_tasks', 'is_cas_authenticated')
    op.drop_column('build_tasks', 'alma_commit_cas_hash')
    op.drop_column('build_artifacts', 'cas_hash')
    op.drop_column('build_task_refs', 'git_commit_hash')
    # ### end Alembic commands ###
