"""Add modularity

Revision ID: 484222016fc0
Revises: c7abd57ad0c0
Create Date: 2021-10-30 19:06:48.947557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484222016fc0'
down_revision = 'c7abd57ad0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpm_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('version', sa.TEXT(), nullable=False),
    sa.Column('stream', sa.TEXT(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=False),
    sa.Column('arch', sa.TEXT(), nullable=False),
    sa.Column('pulp_href', sa.TEXT(), nullable=False),
    sa.Column('sha256', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('build_tasks', sa.Column('rpm_module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'build_tasks', 'rpm_module', ['rpm_module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'build_tasks', type_='foreignkey')
    op.drop_column('build_tasks', 'rpm_module_id')
    op.drop_table('rpm_module')
    # ### end Alembic commands ###
