"""Adjust user_oauth_account access_token length

Revision ID: 4d128cf0914b
Revises: e4b4a298844b
Create Date: 2023-12-26 13:49:22.512022

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d128cf0914b'
down_revision = 'e4b4a298844b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_oauth_accounts',
        'access_token',
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_oauth_accounts',
        'access_token',
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
