"""Added new fields for ErrataRecord

Revision ID: 4d3110a6e11d
Revises: 0154a4bc6ea0
Create Date: 2022-10-24 18:06:52.022520

"""
from alembic import op
import sqlalchemy as sa

from alws.constants import ErrataReleaseStatus


# revision identifiers, used by Alembic.
revision = "4d3110a6e11d"
down_revision = "0154a4bc6ea0"
branch_labels = None
depends_on = None


def upgrade():
    enum = sa.Enum(ErrataReleaseStatus, name="erratareleasestatus")
    enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "errata_records",
        sa.Column(
            "release_status",
            sa.Enum(
                "NOT_RELEASED",
                "IN_PROGRESS",
                "RELEASED",
                "FAILED",
                name="erratareleasestatus",
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "errata_records", sa.Column("last_release_log", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("errata_records", "last_release_log")
    op.drop_column("errata_records", "release_status")
    # ### end Alembic commands ###
    enum = sa.Enum(ErrataReleaseStatus, name="erratareleasestatus")
    enum.drop(op.get_bind())
