"""Add files signature flag to sign key

Revision ID: 4da0f9b95929
Revises: e952dc755f9d
Create Date: 2024-08-28 07:36:35.776846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da0f9b95929'
down_revision = 'e952dc755f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sign_keys', sa.Column('add_files_signature', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign_keys', 'add_files_signature')
    # ### end Alembic commands ###
