"""Add devel_module to NewErrataRecord

Revision ID: 4f39fa73cff4
Revises: bf866d7aed7a
Create Date: 2024-12-11 09:31:54.811229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f39fa73cff4'
down_revision = 'bf866d7aed7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_errata_records', sa.Column('devel_module', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_errata_records', 'devel_module')
    # ### end Alembic commands ###
