"""Added releases

Revision ID: 504d7c7bee33
Revises: 38cb9a229d07
Create Date: 2021-10-22 11:00:15.967332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '504d7c7bee33'
down_revision = '38cb9a229d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_ids', sa.ARRAY(sa.Integer(), dimensions=1), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_rpms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['build_artifacts.id'], ),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binary_rpms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('source_rpm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['build_artifacts.id'], ),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['source_rpm_id'], ['source_rpms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('builds', sa.Column('release_id', sa.Integer(), nullable=True))
    op.add_column('builds', sa.Column('released', sa.Boolean(), nullable=True))
    op.create_foreign_key('build_releases_id_fkey', 'builds', 'build_releases', ['release_id'], ['id'])
    op.add_column('repositories', sa.Column('production', sa.Boolean(), default=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'production')
    op.drop_constraint('build_releases_id_fkey', 'builds', type_='foreignkey')
    op.drop_column('builds', 'released')
    op.drop_column('builds', 'release_id')
    op.drop_table('binary_rpms')
    op.drop_table('source_rpms')
    op.drop_table('build_releases')
    # ### end Alembic commands ###
