"""Added secure boot tasks

Revision ID: 601fc733a869
Revises: 2e1d89155486
Create Date: 2022-01-23 10:05:11.343144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601fc733a869'
down_revision = '2e1d89155486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_tasks', sa.Column('is_secure_boot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_tasks', 'is_secure_boot')
    # ### end Alembic commands ###
