"""Added OVAL title field

Revision ID: 6380c3315c6e
Revises: ec505e94fd1a
Create Date: 2022-09-08 12:18:28.614666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6380c3315c6e'
down_revision = '686a5fae4def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errata_records', sa.Column('oval_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('errata_records', 'oval_title')
    # ### end Alembic commands ###
