"""Add stats for test tasks

Revision ID: 673251e8ca0c
Revises: e2a858195e3a
Create Date: 2023-02-24 10:34:01.582056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673251e8ca0c'
down_revision = 'e2a858195e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_stats', sa.Column('test_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key('perf_stats_test_task_id', 'performance_stats', 'test_tasks', ['test_task_id'], ['id'])
    op.add_column('test_tasks', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('test_tasks', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('test_tasks', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_tasks', 'finished_at')
    op.drop_column('test_tasks', 'started_at')
    op.drop_column('test_tasks', 'scheduled_at')
    op.drop_constraint('perf_stats_test_task_id', 'performance_stats', type_='foreignkey')
    op.drop_column('performance_stats', 'test_task_id')
    # ### end Alembic commands ###
