"""platform id for a repository

Revision ID: 686a5fae4def
Revises: ec505e94fd1a
Create Date: 2022-09-08 07:54:47.089045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686a5fae4def'
down_revision = 'ec505e94fd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key('repositories_platform_id_fkey', 'repositories', 'platforms', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('repositories_platform_id_fkey', 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'platform_id')
    # ### end Alembic commands ###
