"""add priority to repositories

Revision ID: 7469773f4f79
Revises: 3da2d1e48185
Create Date: 2022-02-17 09:36:28.521829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7469773f4f79'
down_revision = '3da2d1e48185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('priority', sa.Integer(), nullable=True))
    op.execute("UPDATE repositories SET priority = 10")
    op.alter_column('repositories', 'priority', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'priority')
    # ### end Alembic commands ###
