"""Integrated fastapi-users

Revision ID: 761f4aae2712
Revises: fad009ddf89a
Create Date: 2022-07-06 14:37:35.747947

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision = '761f4aae2712'
down_revision = 'fad009ddf89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_access_tokens',
        sa.Column('token', sa.String(length=43), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, default=sa.func.now()),
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('token', 'id')
    )
    op.create_index(op.f('ix_user_access_tokens_created_at'), 'user_access_tokens', ['created_at'], unique=False)
    op.create_table(
        'user_oauth_accounts',
        sa.Column('oauth_name', sa.String(length=100), nullable=False),
        sa.Column('access_token', sa.String(length=1024), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('refresh_token', sa.String(length=1024), nullable=True),
        sa.Column('account_id', sa.String(length=320), nullable=False),
        sa.Column('account_email', sa.String(length=320), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_accounts_account_id'), 'user_oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_oauth_accounts_oauth_name'), 'user_oauth_accounts', ['oauth_name'], unique=False)

    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE users SET is_active = true"))
    op.alter_column('users', 'is_active', nullable=False)

    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE users SET is_superuser = false"))
    op.alter_column('users', 'is_superuser', nullable=False)

    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE users SET is_verified = true"))
    op.alter_column('users', 'is_verified', nullable=False)

    op.add_column('users', sa.Column('first_name', sa.String(length=320), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=320), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'jwt_token')
    op.drop_column('users', 'github_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('jwt_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_index(op.f('ix_user_oauth_accounts_oauth_name'), table_name='user_oauth_accounts')
    op.drop_index(op.f('ix_user_oauth_accounts_account_id'), table_name='user_oauth_accounts')
    op.drop_table('user_oauth_accounts')
    op.drop_index(op.f('ix_user_access_tokens_created_at'), table_name='user_access_tokens')
    op.drop_table('user_access_tokens')
    # ### end Alembic commands ###
