"""adding pgp_key for platform

Revision ID: 764a67b23038
Revises: 444f9f1f0ac1
Create Date: 2024-10-25 10:24:17.422595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764a67b23038'
down_revision = '444f9f1f0ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('pgp_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'pgp_key')
    # ### end Alembic commands ###
