"""Add mock options

Revision ID: 76eec955d203
Revises: c221ef0efa07
Create Date: 2021-10-05 19:07:13.661967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "76eec955d203"
down_revision = "c221ef0efa07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "builds",
        sa.Column(
            "mock_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("builds", "mock_options")
    # ### end Alembic commands ###
