"""Add cancel_testing to builds

Revision ID: 79b5458320de
Revises: 4d128cf0914b
Create Date: 2024-01-23 14:51:19.308507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b5458320de'
down_revision = '4d128cf0914b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('cancel_testing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builds', 'cancel_testing')
    # ### end Alembic commands ###
