"""Added cascade deletion for Teams

Revision ID: 82ca9f209b4b
Revises: 1f68a6981a68
Create Date: 2022-07-26 15:25:56.887136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ca9f209b4b'
down_revision = '1f68a6981a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_mapping_role_id_fkey', 'user_role_mapping', type_='foreignkey')
    op.drop_constraint('user_role_mapping_user_id_fkey', 'user_role_mapping', type_='foreignkey')
    op.create_foreign_key('fk_user_role_mapping_user_id', 'user_role_mapping', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_role_mapping_role_id', 'user_role_mapping', 'user_roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_role_mapping_role_id', 'user_role_mapping', type_='foreignkey')
    op.drop_constraint('fk_user_role_mapping_user_id', 'user_role_mapping', type_='foreignkey')
    op.create_foreign_key('user_role_mapping_user_id_fkey', 'user_role_mapping', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_role_mapping_role_id_fkey', 'user_role_mapping', 'user_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
