"""Add test configuration field for build ref

Revision ID: 8f112c94193b
Revises: b924266af778
Create Date: 2023-09-07 08:02:21.757325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f112c94193b'
down_revision = 'b924266af778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_task_refs', sa.Column('test_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_task_refs', 'test_configuration')
    # ### end Alembic commands ###
