"""Adding fkeys for build artifacts and signkey

Revision ID: 936845bf5a4f
Revises: aa0a3bdf68d4
Create Date: 2022-01-25 10:25:55.307940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936845bf5a4f'
down_revision = 'aa0a3bdf68d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_artifacts', sa.Column('sign_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key('build_artifacts_sign_key_id_fkey', 'build_artifacts', 'sign_keys', ['sign_key_id'], ['id'])
    op.add_column('sign_keys', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key('sign_keys_platform_id_fkey', 'sign_keys', 'platforms', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sign_keys_platform_id_fkey', 'sign_keys', type_='foreignkey')
    op.drop_column('sign_keys', 'platform_id')
    op.drop_constraint('build_artifacts_sign_key_id_fkey', 'build_artifacts', type_='foreignkey')
    op.drop_column('build_artifacts', 'sign_key_id')
    # ### end Alembic commands ###
