"""Adjust NewErrataRecords data model after new errata worfklow

Revision ID: 9977cc722e24
Revises: 764a67b23038
Create Date: 2024-11-13 09:26:15.438272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9977cc722e24'
down_revision = '764a67b23038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_errata_records', 'status',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('new_errata_records', 'version',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('new_errata_records', 'definition_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('new_errata_records', 'definition_version',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('new_errata_records', 'definition_class',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('new_errata_records', 'affected_cpe',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('new_errata_records', 'affected_cpe',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('new_errata_records', 'definition_class',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('new_errata_records', 'definition_version',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('new_errata_records', 'definition_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('new_errata_records', 'version',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('new_errata_records', 'status',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
