"""Added cascade deletion for Teams

Revision ID: 9c9b0fdc1a7f
Revises: 1f68a6981a68
Create Date: 2022-07-27 12:55:24.810680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c9b0fdc1a7f"
down_revision = "1f68a6981a68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "action_role_mapping_role_id_fkey", "action_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "action_role_mapping_action_id_fkey", "action_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_action_role_mapping_action_id",
        "action_role_mapping",
        "user_actions",
        ["action_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_action_role_mapping_role_id",
        "action_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_distributions_name", table_name="distributions")
    op.create_index(
        op.f("ix_distributions_name"), "distributions", ["name"], unique=True
    )
    op.drop_constraint(
        "product_role_mapping_product_id_fkey",
        "product_role_mapping",
        type_="foreignkey",
    )
    op.drop_constraint(
        "product_role_mapping_role_id_fkey", "product_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_product_role_mapping_product_id",
        "product_role_mapping",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_product_role_mapping_role_id",
        "product_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "sign_key_role_mapping_role_id_fkey",
        "sign_key_role_mapping",
        type_="foreignkey",
    )
    op.drop_constraint(
        "sign_key_role_mapping_sign_key_id_fkey",
        "sign_key_role_mapping",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_sign_key_role_mapping_sign_key_id",
        "sign_key_role_mapping",
        "sign_keys",
        ["sign_key_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_sign_key_role_mapping_role_id",
        "sign_key_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "team_role_mapping_team_id_fkey", "team_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "team_role_mapping_role_id_fkey", "team_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_team_role_mapping_role_id",
        "team_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_team_role_mapping_team_id",
        "team_role_mapping",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "user_role_mapping_user_id_fkey", "user_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "user_role_mapping_role_id_fkey", "user_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_user_role_mapping_user_id",
        "user_role_mapping",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_user_role_mapping_role_id",
        "user_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_role_mapping_role_id", "user_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_user_role_mapping_user_id", "user_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "user_role_mapping_role_id_fkey",
        "user_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_role_mapping_user_id_fkey",
        "user_role_mapping",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "fk_team_role_mapping_team_id", "team_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_team_role_mapping_role_id", "team_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "team_role_mapping_role_id_fkey",
        "team_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "team_role_mapping_team_id_fkey",
        "team_role_mapping",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.drop_constraint(
        "fk_sign_key_role_mapping_role_id", "sign_key_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_sign_key_role_mapping_sign_key_id",
        "sign_key_role_mapping",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "sign_key_role_mapping_sign_key_id_fkey",
        "sign_key_role_mapping",
        "sign_keys",
        ["sign_key_id"],
        ["id"],
    )
    op.create_foreign_key(
        "sign_key_role_mapping_role_id_fkey",
        "sign_key_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
    )
    op.drop_constraint(
        "fk_product_role_mapping_role_id", "product_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_product_role_mapping_product_id", "product_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "product_role_mapping_role_id_fkey",
        "product_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "product_role_mapping_product_id_fkey",
        "product_role_mapping",
        "products",
        ["product_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_distributions_name"), table_name="distributions")
    op.create_index("ix_distributions_name", "distributions", ["name"], unique=False)
    op.drop_constraint(
        "fk_action_role_mapping_role_id", "action_role_mapping", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_action_role_mapping_action_id", "action_role_mapping", type_="foreignkey"
    )
    op.create_foreign_key(
        "action_role_mapping_action_id_fkey",
        "action_role_mapping",
        "user_actions",
        ["action_id"],
        ["id"],
    )
    op.create_foreign_key(
        "action_role_mapping_role_id_fkey",
        "action_role_mapping",
        "user_roles",
        ["role_id"],
        ["id"],
    )
    # ### end Alembic commands ###
