"""Add modularity

Revision ID: 9cfe8b950c70
Revises: 504d7c7bee33
Create Date: 2021-11-14 17:43:17.270574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cfe8b950c70'
down_revision = '504d7c7bee33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpm_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('version', sa.TEXT(), nullable=False),
    sa.Column('stream', sa.TEXT(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=False),
    sa.Column('arch', sa.TEXT(), nullable=False),
    sa.Column('pulp_href', sa.TEXT(), nullable=False),
    sa.Column('sha256', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('build_tasks', sa.Column('rpm_module_id', sa.Integer(), nullable=True))
    op.add_column('build_tasks', sa.Column('mock_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'build_tasks', 'rpm_module', ['rpm_module_id'], ['id'])
    op.add_column('platforms', sa.Column('module_build_index', sa.Integer(), nullable=True))
    op.add_column('platforms', sa.Column('module_version_prefix', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'module_version_prefix')
    op.drop_column('platforms', 'module_build_index')
    op.drop_constraint(None, 'build_tasks', type_='foreignkey')
    op.drop_column('build_tasks', 'mock_options')
    op.drop_column('build_tasks', 'rpm_module_id')
    op.drop_table('rpm_module')
    # ### end Alembic commands ###
