"""added_built_srpm_url

Revision ID: 9f53bc662376
Revises: aa0a3bdf68d4
Create Date: 2021-12-31 09:53:35.787933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f53bc662376'
down_revision = 'aa0a3bdf68d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_tasks', sa.Column('built_srpm_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_tasks', 'built_srpm_url')
    # ### end Alembic commands ###
