"""added_builted_srpm_url

Revision ID: a3f6778d2499
Revises: e88b665182b9
Create Date: 2021-12-26 16:47:30.823966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f6778d2499'
down_revision = 'e88b665182b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_tasks', sa.Column('builted_srpm_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_tasks', 'builted_srpm_url')
    # ### end Alembic commands ###
