"""Modularity fixes

Revision ID: a8007f32ebc7
Revises: 585ab06efb32
Create Date: 2021-12-08 12:29:46.943350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8007f32ebc7"
down_revision = "585ab06efb32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platforms",
        sa.Column("modularity", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("platforms", "module_version_prefix")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platforms",
        sa.Column(
            "module_version_prefix", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("platforms", "modularity")
    # ### end Alembic commands ###
