"""Added ability to generate sign keys

Revision ID: a89c8723f428
Revises: 76855243a038
Create Date: 2022-10-05 10:45:13.111874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89c8723f428'
down_revision = '0154a4bc6ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sign_key_generation_tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='skgt_product_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='skgt_user_id_fkey'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sign_keys', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column(
        'sign_keys', 'keyid',
        existing_type=sa.VARCHAR(length=16),
        nullable=False
    )
    op.alter_column(
        'sign_keys', 'fingerprint',
        existing_type=sa.VARCHAR(length=40),
        nullable=False
    )
    op.create_foreign_key('sign_keys_product_id_fkey', 'sign_keys', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sign_keys_product_id_fkey', 'sign_keys', type_='foreignkey')
    op.alter_column(
        'sign_keys', 'fingerprint',
        existing_type=sa.VARCHAR(length=40),
        nullable=True)
    op.alter_column(
        'sign_keys', 'keyid',
        existing_type=sa.VARCHAR(length=16),
        nullable=True)
    op.drop_column('sign_keys', 'product_id')
    op.drop_table('sign_key_generation_tasks')
    # ### end Alembic commands ###
