"""add remote_url to repositories

Revision ID: bec2fe94bb02
Revises: 3da2d1e48185
Create Date: 2022-02-16 17:36:40.298834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec2fe94bb02'
down_revision = '3da2d1e48185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('remote_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'remote_url')
    # ### end Alembic commands ###
