"""Add meta field in BuildTaskArtifacts

Revision ID: bf866d7aed7a
Revises: 63bc4e0b699f
Create Date: 2024-12-03 00:40:12.606988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf866d7aed7a'
down_revision = '63bc4e0b699f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_artifacts', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_artifacts', 'meta')
    # ### end Alembic commands ###
