"""Add some indexes

Revision ID: cd510df3fa78
Revises: 3770d10ce787
Create Date: 2023-04-10 16:30:15.123492

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd510df3fa78"
down_revision = "3770d10ce787"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_build_artifacts_build_task_id_name_type",
        "build_artifacts",
        ["build_task_id", "name", "type"],
        unique=False,
    )
    op.create_index(
        "idx_build_artifacts_build_task_id_type",
        "build_artifacts",
        ["build_task_id", "type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_build_artifacts_build_task_id"),
        "build_artifacts",
        ["build_task_id"],
        unique=False,
    )
    op.create_index(
        "idx_build_tasks_build_id_index",
        "build_tasks",
        ["build_id", "index"],
        unique=False,
    )
    op.create_index(
        "idx_build_tasks_build_id_index_status",
        "build_tasks",
        ["build_id", "index", "status"],
        unique=False,
    )
    op.create_index(
        "idx_build_tasks_build_id_status",
        "build_tasks",
        ["build_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_build_tasks_status_arch_ts",
        "build_tasks",
        ["status", "arch", "ts"],
        unique=False,
    )
    op.create_index(
        op.f("ix_build_tasks_arch"), "build_tasks", ["arch"], unique=False
    )
    op.create_index(
        op.f("ix_build_tasks_build_id"),
        "build_tasks",
        ["build_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_build_tasks_ref_id"), "build_tasks", ["ref_id"], unique=False
    )
    op.create_index(
        op.f("ix_build_tasks_status"), "build_tasks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_build_tasks_ts"), "build_tasks", ["ts"], unique=False
    )
    op.create_index(
        "idx_errata_packages_name_version",
        "errata_packages",
        ["name", "version"],
        unique=False,
    )
    op.create_index(
        "idx_errata_packages_name_version_arch",
        "errata_packages",
        ["name", "version", "arch"],
        unique=False,
    )
    op.create_index(
        op.f("ix_errata_packages_errata_record_id"),
        "errata_packages",
        ["errata_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_errata_references_errata_record_id"),
        "errata_references",
        ["errata_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_errata_to_albs_packages_errata_package_id"),
        "errata_to_albs_packages",
        ["errata_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_stats_build_task_id"),
        "performance_stats",
        ["build_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_stats_release_id"),
        "performance_stats",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_performance_stats_test_task_id"),
        "performance_stats",
        ["test_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_rpms_build_id"),
        "source_rpms",
        ["build_id"],
        unique=False,
    )
    op.create_index(
        "idx_test_tasks_build_task_id_revision",
        "test_tasks",
        ["build_task_id", "revision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_tasks_build_task_id"),
        "test_tasks",
        ["build_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_tasks_revision"),
        "test_tasks",
        ["revision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_tasks_status"), "test_tasks", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_tasks_status"), table_name="test_tasks")
    op.drop_index(op.f("ix_test_tasks_revision"), table_name="test_tasks")
    op.drop_index(op.f("ix_test_tasks_build_task_id"), table_name="test_tasks")
    op.drop_index(
        "idx_test_tasks_build_task_id_revision", table_name="test_tasks"
    )
    op.drop_index(op.f("ix_source_rpms_build_id"), table_name="source_rpms")
    op.drop_index(
        op.f("ix_performance_stats_test_task_id"),
        table_name="performance_stats",
    )
    op.drop_index(
        op.f("ix_performance_stats_release_id"), table_name="performance_stats"
    )
    op.drop_index(
        op.f("ix_performance_stats_build_task_id"),
        table_name="performance_stats",
    )
    op.drop_index(
        op.f("ix_errata_to_albs_packages_errata_package_id"),
        table_name="errata_to_albs_packages",
    )
    op.drop_index(
        op.f("ix_errata_references_errata_record_id"),
        table_name="errata_references",
    )
    op.drop_index(
        op.f("ix_errata_packages_errata_record_id"),
        table_name="errata_packages",
    )
    op.drop_index(
        "idx_errata_packages_name_version_arch", table_name="errata_packages"
    )
    op.drop_index(
        "idx_errata_packages_name_version", table_name="errata_packages"
    )
    op.drop_index(op.f("ix_build_tasks_ts"), table_name="build_tasks")
    op.drop_index(op.f("ix_build_tasks_status"), table_name="build_tasks")
    op.drop_index(op.f("ix_build_tasks_ref_id"), table_name="build_tasks")
    op.drop_index(op.f("ix_build_tasks_build_id"), table_name="build_tasks")
    op.drop_index(op.f("ix_build_tasks_arch"), table_name="build_tasks")
    op.drop_index("idx_build_tasks_status_arch_ts", table_name="build_tasks")
    op.drop_index("idx_build_tasks_build_id_status", table_name="build_tasks")
    op.drop_index(
        "idx_build_tasks_build_id_index_status", table_name="build_tasks"
    )
    op.drop_index("idx_build_tasks_build_id_index", table_name="build_tasks")
    op.drop_index(
        op.f("ix_build_artifacts_build_task_id"), table_name="build_artifacts"
    )
    op.drop_index(
        "idx_build_artifacts_build_task_id_type", table_name="build_artifacts"
    )
    op.drop_index(
        "idx_build_artifacts_build_task_id_name_type",
        table_name="build_artifacts",
    )
    # ### end Alembic commands ###
