"""add priority to repositories

Revision ID: d8dd099dc849
Revises: 6f8e782397d2
Create Date: 2022-02-09 14:45:37.608420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dd099dc849'
down_revision = '6f8e782397d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('priority', sa.Integer(), nullable=True))
    op.execute("UPDATE repositories SET priority = 10")
    op.alter_column('repositories', 'priority', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'priority')
    # ### end Alembic commands ###
