"""Temporary null username

Revision ID: db7ffc2bc642
Revises: 761f4aae2712
Create Date: 2022-07-08 15:16:45.029319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7ffc2bc642'
down_revision = '761f4aae2712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
