"""Added time fields for sign_tasks

Revision ID: e2a858195e3a
Revises: 75c60c8151d5
Create Date: 2023-02-22 17:04:53.279986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2a858195e3a"
down_revision = "75c60c8151d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sign_tasks", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("sign_tasks", sa.Column("finished_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sign_tasks", "finished_at")
    op.drop_column("sign_tasks", "started_at")
    # ### end Alembic commands ###
