"""Added cascade deletion to artifact_id in errata_to_albs_packages table

Revision ID: e4b4a298844b
Revises: cd510df3fa79
Create Date: 2023-10-13 10:54:15.091008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b4a298844b'
down_revision = 'cd510df3fa79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('errata_to_albs_packages_albs_artifact_id_fkey', 'errata_to_albs_packages', type_='foreignkey')
    op.create_foreign_key('errata_to_albs_packages_albs_artifact_id_fkey', 'errata_to_albs_packages', 'build_artifacts', ['albs_artifact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('errata_to_albs_packages_albs_artifact_id_fkey', 'errata_to_albs_packages', type_='foreignkey')
    op.create_foreign_key('errata_to_albs_packages_albs_artifact_id_fkey', 'errata_to_albs_packages', 'build_artifacts', ['albs_artifact_id'], ['id'])
    # ### end Alembic commands ###
