"""Allow empty cvss3 score in CVEs

Revision ID: e9bb2a44defb
Revises: 4f39fa73cff4
Create Date: 2025-03-17 22:34:58.442894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bb2a44defb'
down_revision = '4f39fa73cff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('errata_cves', 'cvss3',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('errata_cves', 'cvss3',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
