"""Added community release flow

Revision ID: ec505e94fd1a
Revises: 26b384d3493f
Create Date: 2022-08-18 07:38:00.361373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec505e94fd1a'
down_revision = '26b384d3493f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_releases', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key('build_releases_product_id_fkey', 'build_releases', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('is_community', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE products SET is_community = true"))
    op.alter_column('products', 'is_community', nullable=False)
    op.create_foreign_key('build_releases_team_id_fkey', 'build_releases', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_community')
    op.drop_constraint('build_releases_team_id_fkey', 'build_releases', type_='foreignkey')
    op.drop_constraint('build_releases_product_id_fkey', 'build_releases', type_='foreignkey')
    op.drop_column('build_releases', 'product_id')
    # ### end Alembic commands ###
