name: check-migrations
on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Check out repository
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Configure git and fetch origin/master
        run: |
          git config --global user.email "action@users.noreply.github.com"
          git config --global user.name "action"
          git fetch origin master
      - name: Rebase
        id: rebase
        run: |
          git rebase origin/master
        continue-on-error: true
      - name: Merge
        if: steps.rebase.outcome != 'success'
        run: |
          git rebase --abort
          git merge --no-ff --no-log origin/master
      - name: Create dirs and files
        run: |
          mkdir -p ../{alts,albs-frontend,albs-node,albs-sign-file,albs-sign-node,alma-tests-cacher}
          touch ../albs-sign-file/.env
          ln -sf tests/test-vars.env vars.env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: web-server-tests
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Start services
        run: docker compose up -d test_db
      - name: Check migrations
        run: docker compose run --rm web_server_tests alembic --config tests/test-alembic.ini upgrade head
      - name: Stop services
        if: always()
        run: docker compose down --volumes
