name: Pull Request Checks
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

defaults:
  run:
    shell: bash

jobs:
  check-pr-message:
    runs-on: ubuntu-latest
    steps:

      - name: Check the PR title
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{1,72}$'
          excludeTitle: 'false'
          excludeDescription: 'true'
          error: 'The maximum line length of 72 characters is exceeded.'

      - name: Check the PR description
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(Resolves|Fixes):? +(https:\/\/github.com\/)?AlmaLinux\/build-system(\/issues\/|#)[0-9]+'
          error: 'You need at least one "Resolves|Fixes: <issue link>" line.'
