name: syntax
on:
  pull_request_target:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.py
      - name: Install python packages
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: pip install -r requirements-tests.txt
      - name: Run pylint
        id: pylint
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "report<<$delimiter" >> $GITHUB_OUTPUT
          pylint ${{ steps.changed-files.outputs.all_changed_files }} --py-version 3.9 --exit-zero >> $GITHUB_OUTPUT
          echo $delimiter >> $GITHUB_OUTPUT
      - name: Post pylint output
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          message: |
            <details>
              <summary>pylint output</summary>

            ```
            ${{ steps.pylint.outputs.report }}
            ```
            </details>
          message-id: pylint-report
      - name: Run black
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: black ${{ steps.changed-files.outputs.all_changed_files }} --exclude alws/alembic --check --diff --color --target-version py39
      - name: Run isort
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: isort ${{ steps.changed-files.outputs.all_changed_files }} --diff --color --check-only --py 39
